build:  Switch to '-Os' as default for all targets, and enable -Wextra
(sh and m68k already used -Os, as did some arm targets)

This leaves alone plugin/codec-specific optimization flags

(Personally tested on mini2g, nano2g, xduoox3, clipplus, and agptekrocker)

Change-Id: Ic64aeef983c7fe93ba6e49bec14a180c7d977035

diff --git a/tools/configure b/tools/configure
--- a/tools/configure
+++ b/tools/configure
@@ -8,7 +8,7 @@
 #
 
 # global CC options for all platforms
-CCOPTS="-W -Wall -Wundef -O -nostdlib -ffreestanding -Wstrict-prototypes -pipe -std=gnu99"
+CCOPTS="-W -Wall -Wextra -Wundef -Os -nostdlib -ffreestanding -Wstrict-prototypes -pipe -std=gnu99 -funit-at-a-time"
 
 # LD options for the core
 LDOPTS=""
@@ -2791,7 +2791,6 @@ fi
     t_model="sansa-clip"
     if [ "$ARG_ARM_THUMB" != 0 ]; then ARG_ARM_THUMB=1; fi
     arm9tdmicc
-    GCCOPTS=`echo $GCCOPTS | sed 's/ -O / -Os /'`
     ;;
 
 
@@ -2835,7 +2834,6 @@ fi
     t_model="sansa-m200v4"
     if [ "$ARG_ARM_THUMB" != 0 ]; then ARG_ARM_THUMB=1; fi
     arm9tdmicc
-    GCCOPTS=`echo $GCCOPTS | sed 's/ -O / -Os /'`
     ;;
 
 
@@ -2882,7 +2880,6 @@ fi
     t_model="sansa-c200v2"
     if [ "$ARG_ARM_THUMB" != 0 ]; then ARG_ARM_THUMB=1; fi
     arm9tdmicc
-    GCCOPTS=`echo $GCCOPTS | sed 's/ -O / -Os /'`
     ;;
 
    60|sansaclipv2)
@@ -4768,18 +4765,12 @@ if test "$CC" = "sh-elf-gcc"; then
 
     if { echo $gccpatch | grep "rockbox" >/dev/null 2>&1; } then
       echo "gcc $gccver is rockbox patched"
-      # then convert -O to -Os to get smaller binaries!
-      GCCOPTS=`echo $GCCOPTS | sed 's/ -O / -Os /'`
     else
-      echo "WARNING: You use an unpatched gcc compiler: $gccver"
-      echo "WARNING: http://www.rockbox.org/twiki/bin/view/Main/CrossCompiler"
+      echo "ERROR: You use an unpatched gcc compiler: $gccver"
+      echo "ERROR: http://www.rockbox.org/twiki/bin/view/Main/CrossCompiler"
+      exit 1;
     fi
   fi
-fi
-
-if test "$CC" = "m68k-elf-gcc"; then
-  # convert -O to -Os to get smaller binaries!
-  GCCOPTS=`echo $GCCOPTS | sed 's/ -O / -Os /'`
 fi
 
 if [ "$ARG_CCACHE" = "1" ]; then
